/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package groupproject;

import java.awt.Color;
import java.awt.Font;
import java.time.LocalDate;

/**
 *
 * @author Yash Shah
 */
public class CalendarLooknew extends javax.swing.JFrame {

    /**
     * Creates new form CalendarLooknew
     */
    static CalendarLooknew cL;
    String[] fD = new String[40];
    
    public CalendarLooknew(int month, int year) {
        String[] finalDates  = calcDate(month, year);
        fD = finalDates.clone();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("jButton1");
        jButton1.setText(fD[0]);
        jButton1.setBackground(new Color(192, 192, 192));
        jButton1.setForeground(Color.BLACK);
        jButton1.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton1.setBorder(null);

        jButton2.setText("jButton2");
        jButton2.setText(fD[1]);
        jButton2.setBackground(new Color(192, 192, 192));
        jButton2.setForeground(Color.BLACK);
        jButton2.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton2.setBorder(null);

        jButton3.setText("jButton3");
        jButton3.setText(fD[2]);
        jButton3.setBackground(new Color(192, 192, 192));
        jButton3.setForeground(Color.BLACK);
        jButton3.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton3.setBorder(null);

        jButton4.setText("jButton4");
        jButton4.setText(fD[3]);
        jButton4.setBackground(new Color(192, 192, 192));
        jButton4.setForeground(Color.BLACK);
        jButton4.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton4.setBorder(null);

        jButton5.setText("jButton5");
        jButton5.setText(fD[4]);
        jButton5.setBackground(new Color(192, 192, 192));
        jButton5.setForeground(Color.BLACK);
        jButton5.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton5.setBorder(null);

        jButton6.setText("jButton6");
        jButton6.setText(fD[5]);
        jButton6.setBackground(new Color(192, 192, 192));
        jButton6.setForeground(Color.BLACK);
        jButton6.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton6.setBorder(null);

        jButton7.setText("jButton7");
        jButton7.setText(fD[6]);
        jButton7.setBackground(new Color(192, 192, 192));
        jButton7.setForeground(Color.BLACK);
        jButton7.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("jButton8");
        jButton8.setText(fD[7]);
        jButton8.setBackground(new Color(192, 192, 192));
        jButton8.setForeground(Color.BLACK);
        jButton8.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton8.setBorder(null);

        jButton9.setText("jButton9");
        jButton9.setText(fD[8]);
        jButton9.setBackground(new Color(192, 192, 192));
        jButton9.setForeground(Color.BLACK);
        jButton9.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton9.setBorder(null);

        jButton10.setText("jButton10");
        jButton10.setText(fD[20]);
        jButton10.setBackground(new Color(192, 192, 192));
        jButton10.setForeground(Color.BLACK);
        jButton10.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton10.setBorder(null);

        jButton11.setText("jButton11");
        jButton11.setText(fD[21]);
        jButton11.setBackground(new Color(192, 192, 192));
        jButton11.setForeground(Color.BLACK);
        jButton11.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton11.setBorder(null);

        jButton12.setText("jButton12");
        jButton12.setText(fD[15]);
        jButton12.setBackground(new Color(192, 192, 192));
        jButton12.setForeground(Color.BLACK);
        jButton12.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton12.setBorder(null);
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton14.setText("jButton14");
        jButton14.setText(fD[9]);
        jButton14.setBackground(new Color(192, 192, 192));
        jButton14.setForeground(Color.BLACK);
        jButton14.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton14.setBorder(null);

        jButton15.setText("jButton15");
        jButton15.setText(fD[10]);
        jButton15.setBackground(new Color(192, 192, 192));
        jButton15.setForeground(Color.BLACK);
        jButton15.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton15.setBorder(null);
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("jButton16");
        jButton16.setText(fD[11]);
        jButton16.setBackground(new Color(192, 192, 192));
        jButton16.setForeground(Color.BLACK);
        jButton16.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton16.setBorder(null);

        jButton17.setText("jButton17");
        jButton17.setText(fD[12]);
        jButton17.setBackground(new Color(192, 192, 192));
        jButton17.setForeground(Color.BLACK);
        jButton17.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton17.setBorder(null);

        jButton18.setText("jButton18");
        jButton18.setText(fD[13]);
        jButton18.setBackground(new Color(192, 192, 192));
        jButton18.setForeground(Color.BLACK);
        jButton18.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton18.setBorder(null);

        jButton19.setText("jButton19");
        jButton19.setText(fD[15]);
        jButton19.setBackground(new Color(192, 192, 192));
        jButton19.setForeground(Color.BLACK);
        jButton19.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton19.setBorder(null);

        jButton13.setText("jButton13");
        jButton13.setText(fD[14]);
        jButton13.setBackground(new Color(192, 192, 192));
        jButton13.setForeground(Color.BLACK);
        jButton13.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton13.setBorder(null);

        jButton20.setText("jButton20");
        jButton20.setText(fD[17]);
        jButton20.setBackground(new Color(192, 192, 192));
        jButton20.setForeground(Color.BLACK);
        jButton20.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton20.setBorder(null);

        jButton21.setText("jButton21");
        jButton21.setText(fD[18]);
        jButton21.setBackground(new Color(192, 192, 192));
        jButton21.setForeground(Color.BLACK);
        jButton21.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton21.setBorder(null);

        jButton22.setText("jButton22");
        jButton22.setText(fD[19]);
        jButton22.setBackground(new Color(192, 192, 192));
        jButton22.setForeground(Color.BLACK);
        jButton22.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton22.setBorder(null);

        jButton23.setText("jButton23");
        jButton23.setText(fD[22]);
        jButton23.setBackground(new Color(192, 192, 192));
        jButton23.setForeground(Color.BLACK);
        jButton23.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton23.setBorder(null);

        jButton24.setText("jButton24");
        jButton24.setText(fD[23]);
        jButton24.setBackground(new Color(192, 192, 192));
        jButton24.setForeground(Color.BLACK);
        jButton24.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton24.setBorder(null);

        jButton25.setText("jButton25");
        jButton25.setText(fD[24]);
        jButton25.setBackground(new Color(192, 192, 192));
        jButton25.setForeground(Color.BLACK);
        jButton25.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton25.setBorder(null);

        jButton26.setText("jButton26");
        jButton26.setText(fD[25]);
        jButton26.setBackground(new Color(192, 192, 192));
        jButton26.setForeground(Color.BLACK);
        jButton26.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton26.setBorder(null);

        jButton27.setText("jButton27");
        jButton27.setText(fD[26]);
        jButton27.setBackground(new Color(192, 192, 192));
        jButton27.setForeground(Color.BLACK);
        jButton27.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton27.setBorder(null);

        jButton28.setText("jButton28");
        jButton28.setText(fD[27]);
        jButton28.setBackground(new Color(192, 192, 192));
        jButton28.setForeground(Color.BLACK);
        jButton28.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton28.setBorder(null);

        jLabel1.setText("MON");

        jLabel2.setText("TUE");

        jLabel3.setText("WED");

        jLabel4.setText("THU");

        jLabel5.setText("FRI");

        jLabel6.setText("SAT");

        jLabel7.setText("SUN");

        jButton29.setText("jButton29");
        jButton29.setText(fD[28]);
        jButton29.setBackground(new Color(192, 192, 192));
        jButton29.setForeground(Color.BLACK);
        jButton29.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton29.setBorder(null);

        jButton30.setText("jButton30");
        jButton30.setText(fD[29]);
        jButton30.setBackground(new Color(192, 192, 192));
        jButton30.setForeground(Color.BLACK);
        jButton30.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton30.setBorder(null);

        jButton31.setText("jButton31");
        jButton31.setText(fD[30]);
        jButton31.setBackground(new Color(192, 192, 192));
        jButton31.setForeground(Color.BLACK);
        jButton31.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton31.setBorder(null);

        jButton32.setText("jButton32");
        jButton32.setText(fD[31]);
        jButton32.setBackground(new Color(192, 192, 192));
        jButton32.setForeground(Color.BLACK);
        jButton32.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton32.setBorder(null);

        jButton33.setText("jButton33");
        jButton33.setText(fD[32]);
        jButton33.setBackground(new Color(192, 192, 192));
        jButton33.setForeground(Color.BLACK);
        jButton33.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton33.setBorder(null);

        jButton34.setText("jButton34");
        jButton34.setText(fD[33]);
        jButton34.setBackground(new Color(192, 192, 192));
        jButton34.setForeground(Color.BLACK);
        jButton34.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton34.setBorder(null);

        jButton35.setText("jButton35");
        jButton35.setText(fD[34]);
        jButton35.setBackground(new Color(192, 192, 192));
        jButton35.setForeground(Color.BLACK);
        jButton35.setFont(new Font("Tahoma", Font.BOLD, 12));
        jButton35.setBorder(null);
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(12, 12, 12)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel3)))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel4))
                            .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(jLabel5)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(13, 13, 13)))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel7))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton33, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jButton34, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                            .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))))))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton10, jButton11, jButton12, jButton13, jButton14, jButton15, jButton16, jButton17, jButton18, jButton19, jButton2, jButton20, jButton21, jButton22, jButton23, jButton24, jButton25, jButton26, jButton27, jButton28, jButton3, jButton4, jButton5, jButton6, jButton7, jButton8, jButton9});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(89, 89, 89)
                        .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton31, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton32, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton33, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton34, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton35, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton10, jButton11, jButton12, jButton13, jButton14, jButton15, jButton16, jButton17, jButton18, jButton19, jButton2, jButton20, jButton21, jButton22, jButton23, jButton24, jButton25, jButton26, jButton27, jButton28, jButton3, jButton4, jButton5, jButton6, jButton7, jButton8, jButton9});

        pack();
    }// </editor-fold>//GEN-END:initComponents
private String[] calcDate(int m, int y){
        
        //get current year
         LocalDate localDate = LocalDate.now();
         
         //year code
        //int year = localDate.getYear();
        int year = y;
        
        int tempYear = Integer.valueOf(String.valueOf(year).substring(2));
        int yearCode = (tempYear + (tempYear/4)) % 7;
        
        
        
        //month code
        int monthCodes[] = new int[]{0,3,3,6,1,4,6,2,5,0,3,5};
        /*
        LocalDate localMonth = LocalDate.now();
        int month = localMonth.getMonthValue();
        int monthCode = monthCodes[month-1]; 
        */
        int month = m;
        int monthCode = monthCodes[m];
        
        
        //Century Code
        int centuryCode = 6; 
        
        //Leap Year 
        int leapCode = 0;
        if((month==1 || month==2)&&year%4==0){
            leapCode = 1;   
        }
        
        //formula for calulating the day 
        //(Year Code + Month Code + Century Code + Date Number – Leap Year Code) mod 7
        
        int day = (yearCode + monthCode + centuryCode + 1 - leapCode)%7;
        
        String[] finalDates = new String[36]; 
        int counter = 0;
        int limit = 0;
        boolean once = false;
        if(month==0 || month==2 || month==4 || month==6 || month==7 || month==9 ||month==11){
            limit = 31;
            
        }
        else if(month==1){
            if(year%4==0){
                limit = 29;
            }
            else{
                limit = 28;
            }
        
        }
        else{
            limit = 30;
        }
        for(int i = 0; i<35; i++){
            
            if(i==day-1){
                counter = 1;
                
                
            }
            else if(i>day-1 && counter<limit && once==false){
                counter++;
            }
            else if(counter>=limit){
                counter=0;
                once = true;
            }
            System.out.println(counter);
            if(counter==0){
                finalDates[i] = "";
            }
            else{
            finalDates[i] = String.valueOf(counter);
            }
        
        }   
        return finalDates;
    }
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton35ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalendarLooknew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalendarLooknew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalendarLooknew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalendarLooknew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                cL.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
